apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  labels:
    app: backend
type: Opaque
stringData:
  database.username: postgres
  database.password: postgres123
  jwt.secret: dGhpcy1pcy1hLXZlcnktbG9uZy1zZWNyZXQta2V5LWZvci1qd3QtdG9rZW4tZ2VuZXJhdGlvbg==
  keycloak.client.secret: claude-ai-bff-secret
  keycloak.admin.client.secret: claude-ai-backend-secret
